version: '2.1'
services:

    #
    # elasticsearch
    #
    elasticsearch:
        image: elasticsearch:7.13.1
        environment:
          - "discovery.type=single-node"
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - 9200:9200
